---
- hosts: all
  vars_files:
  - env_variables_ubuntu
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  - name: Changing iptables
    template: src=k8s.conf dest=/etc/sysctl.d/k8s.conf owner=root group=root
    register: iptables

  - name: Sync the sysctl configuration
    command: sysctl --system
    when: iptables.changed

  - name: Changing iptables
    template: src=k8s-module.conf dest=/etc/modules-load.d/k8s.conf owner=root group=root
    register: iptables_module

  - name: Sync the sysctl configuration
    command: sysctl --system
    when: iptables_module.changed

  - name: Enable probe
    shell: modprobe overlay;modprobe br_netfilter
    when: iptables_module.changed    

  - name: Sync hosts file
    template: src=/etc/hosts dest=/etc/hosts
